steps:
- name: 'gcr.io/cloud-builders/gradle'
  args: ['jmh', '--stacktrace']
- name: 'gcr.io/cloud-builders/gradle'
  args: ['jmhReport', '--stacktrace']
- name: 'gcr.io/cloud-builders/gradle'
  args: ['gitPublishPush', '--stacktrace']

timeout: 3h

artifacts:
  objects:
    location: 'gs://[STORAGE_LOCATION]/kotlin-benchmarks/report'
    paths: 'benchmarks/build/reports/jmh/**'