steps:
- name: 'gcr.io/cloud-builders/gradle'
  args: ['clean', 'build', 'jmh']
- name: 'gcr.io/cloud-builders/gradle'
  args: ['jmhReport']
- name: 'gcr.io/cloud-builders/gradle'
  args: ['gitPublishPush']

timeout: 3h